version: '3'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-prod
    ports:
      - 5000:5000

  backend:
    build: ./backend
    environment:
      host: "0.0.0.0:4000"
      data_dir: "/data"
      jwt_secret: "mikochi_secret_key"
      username: "root"
      password: "pass"
    volumes:
      - ./data:/data
    ports:
      - 4000:4000

  mikochi:
    image: nginx:1.23.3
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80
    volumes:
      - ./nginx-release.conf:/etc/nginx/nginx.conf

  dev-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 5000:5000

  dev-backend:
    image: cosmtrek/air:v1.42.0
    working_dir: "/mikochi"
    environment:
      air_wd: "/mikochi"
      host: "0.0.0.0:4000"
      data_dir: "/data"
      jwt_secret: "mikochi_secret_key"
      username: "root"
      password: "pass"
    volumes:
      - ./backend:/mikochi
      - ./data:/data
    ports:
      - 4000:4000
    command: air -c .air.toml

  dev:
    image: nginx:1.23.3
    depends_on:
      - dev-backend
      - dev-frontend
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
