version: '3'
services:
  mikochi:
    build: ./backend
    ports:
      - 8080:8080

  dev:
    image: cosmtrek/air:v1.40.4
    working_dir: "/mikochi"
    environment:
      air_wd: "/mikochi"
    volumes:
      - ./backend:/mikochi
      - ./backend/data:/data
    ports:
      - 8080:8080
    command: air -c .air.toml
