version: '3'
services:
  mikochi:
    build: .
    volumes:
      - ./data:/data
    ports:
      - 8080:8080

  dev-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 5000:5000

  dev-backend:
    image: cosmtrek/air:v1.42.0
    working_dir: "/mikochi"
    environment:
      air_wd: "/mikochi"
      HOST: "0.0.0.0:4000"
      ENV: "development"
    volumes:
      - ./backend:/mikochi
      - ./data:/data
    ports:
      - 4000:4000
    command: air -c .air.toml

  dev:
    image: nginx:1.23.3
    depends_on:
      - dev-backend
      - dev-frontend
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
