apiVersion: v1
kind: Service
metadata:
  name: {{ include "Mikochi.fullname" . }}
  labels:
    {{- include "Mikochi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "Mikochi.selectorLabels" . | nindent 4 }}
